<?php $this->widget('EExcelView',array(
        'id'=>'invoice-his-grid',
        'fixedHeader' => true,
        //'responsiveTable' => true,
        'type'=>TbHtml::GRID_TYPE_BORDERED,
        'template'=>"{summary}\n{items}\n{exportbuttons}\n{pager}",
        'dataProvider'=>$model->invoice($client_id,'='),
        'summaryText' =>'<p class="text-info"> Invoice Paid History </p>', 
        'htmlOptions'=>array('class'=>'table-responsive panel'),
        'columns'=>array(
            array('name'=>'id',
                'header'=>Yii::t('app','Invoice ID'),
                'type'=>'raw',
                'value'=>'$data["sale_id"]',
            ),
            array('name'=>'sale_time',
                'header'=>Yii::t('app','Sale Time'),
                'value'=>'$data["sale_time"]',
                //'value'=>'CHtml::link($data["sale_time"], Yii::app()->createUrl("saleitem/admin",array("id"=>$data["id"])))',
                //'type'=>'raw',
            ),
            array('name'=>'client_name',
                'header'=>Yii::t('app','Sold To'),
                'value'=>'$data["client_name"]',
            ),
            array('name'=>'employee_name',
                'header'=>Yii::t('app','Sold By'),
                'value'=>'$data["employee_name"]',
            ),
            array('name'=>'sub_total',
                'header'=>Yii::t('app','Sub Total'),
                'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                'value' =>'number_format($data["sub_total"],Common::getDecimalPlace(), ".", ",")',
                'htmlOptions'=>array('style' => 'text-align: right;'),
            ),
            array('name'=>'discount_amount',
                'header'=>Yii::t('app','Discount'),
                'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                'value' =>'number_format($data["discount_amount"],Common::getDecimalPlace(), ".", ",")',
                'htmlOptions'=>array('style' => 'text-align: right;'),
            ),
            array('name'=>'paid',
                'header'=>Yii::t('app','Paid'),
                'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                'value' =>'number_format($data["paid"],Common::getDecimalPlace(), ".", ",")',
                'htmlOptions'=>array('style' => 'text-align: right;'),
            ),
            array('name'=>'balance',
                'header'=>Yii::t('app','Balance'),
                'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                'value' =>'number_format($data["balance"],Common::getDecimalPlace(), ".", ",")',
                'htmlOptions'=>array('style' => 'text-align: right;'),
            ),
            array('name'=>'status',
                'header'=>Yii::t('app','Status'),
                'value'=>'$data["status_f"]',
            ),
            array('class'=>'bootstrap.widgets.TbButtonColumn',
                'header'=>'Action',
                'template'=>'<div class="btn-group">{view}</div>',
                //'htmlOptions'=>array('class'=>'hidden-phone visible-desktop btn-group'),
                'buttons' => array(
                    'view' => array(
                        'click' => 'updateDialogOpen',
                        'label'=>'Detail',
                        'url'=>'Yii::app()->createUrl("report/SaleInvoiceItem", array("sale_id"=>$data["sale_id"],"employee_id"=>$data["employee_name"]))',
                        'options' => array(
                            'data-update-dialog-title' => Yii::t( 'app', 'Invoice Detail' ),
                            //'class'=>'label label-important',
                            'title'=>Yii::t('app','Invoice Detail'),
                            'class'=>'btn btn-xs btn-info',
                            'id'=>uniqid(),
                            'on'=>false,
                        ),
                    ),
                ),
            ),
        ),
));