<?php $this->widget('EExcelView',array(
        'id'=>'invoice-grid',
        'fixedHeader' => true,
        //'responsiveTable' => true,
        'type'=>'striped hover',
        'template'=>"{summary}\n{items}\n{exportbuttons}\n{pager}",
        'dataProvider'=>$model->paymentHis($client_id),
        'summaryText' =>'<p class="text-info"> Payment History </p>', 
        'htmlOptions'=>array('class'=>'table-responsive panel'),
        'columns'=>array(
                array('name'=>'id',
                      'header'=>Yii::t('app','Receipt Number'), 
                      'value'=>'$data["id"]',
                ),
                array('name'=>'client_name',
                      'header'=>Yii::t('app','Customer Name'), 
                      'value'=>'$data["client_name"]',
                ),
                array('name'=>'date_paid',
                      'header'=>Yii::t('app','Date Time'),
                      'value'=>'$data["date_paid"]',
                      //'value'=>'CHtml::link($data["sale_time"], Yii::app()->createUrl("saleitem/admin",array("id"=>$data["id"])))',
                      //'type'=>'raw',
                ),
                array('name'=>'payment_amount',
                      'header'=>Yii::t('app','Amount'),
                      'value'=>'$data["payment_amount"]',
                ),
                array('name'=>'employee_id',
                      'header'=>Yii::t('app','Employee'),
                      'value'=>'$data["employee_name"]',
                ),
                array('name'=>'note',
                      'header'=>Yii::t('app','Payment Note'),
                      'value'=>'$data["note"]',
                ),
        ),
)); ?>   