<?php $this->widget('EExcelView',array(
        'id'=>'invoice-grid',
        'fixedHeader' => true,
        //'responsiveTable' => true,
        'type'=>TbHtml::GRID_TYPE_BORDERED,
        'template'=>"{summary}\n{items}\n{exportbuttons}\n{pager}",
        'dataProvider'=>$model->invoiceHis($supplier_id),
        'summaryText' =>'<p class="text-info"><?php echo ("app","Outstanding Invoices"); ?></p>',
        'htmlOptions'=>array('class'=>'table-responsive panel'),
        'columns'=>array(
                array('name'=>'id',
                      'header'=>Yii::t('app','Invoice ID'),
                      'value'=>'$data["receive_id"]',
                ),
                array('name'=>'supplier_name',
                      'header'=>Yii::t('app','Supplier Name'),
                      'value'=>'$data["supplier_name"]',
                ),
                array('name'=>'receive_time',
                      'header'=>Yii::t('app','Receive Time'),
                      'value'=>'$data["receive_time"]',
                      //'value'=>'CHtml::link($data["sale_time"], Yii::app()->createUrl("saleitem/admin",array("id"=>$data["id"])))',
                      //'type'=>'raw',
                ),
                array('name'=>'sub_total',
                      'header'=>Yii::t('app','Sub Total'),   
                      'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                      'value' =>'number_format($data["sub_total"],Common::getDecimalPlace(), ".", ",")',
                      'htmlOptions'=>array('style' => 'text-align: right;'),
                ),
                array('name'=>'discount_amount',
                      'header'=>Yii::t('app','Discount'),   
                      'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                      'value' =>'number_format($data["discount_amount"],Common::getDecimalPlace(), ".", ",")',
                      'htmlOptions'=>array('style' => 'text-align: right;'),
                ),
                array('name'=>'paid',
                      'header'=>Yii::t('app','Paid'),   
                      'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                      'value' =>'number_format($data["paid"],Common::getDecimalPlace(), ".", ",")',
                      'htmlOptions'=>array('style' => 'text-align: right;'),
                ),
                array('name'=>'balance',
                      'header'=>Yii::t('app','Balance'),   
                      'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                      'value' =>'number_format($data["balance"],Common::getDecimalPlace(), ".", ",")',
                      'htmlOptions'=>array('style' => 'text-align: right;'),
                      //'footer'=> number_format($balance,Common::getDecimalPlace(),'.', ','),
                      //'footerHtmlOptions'=>array('style' => 'text-align: right;'),
                ),
        ),
)); ?>   